<program>     ::= { <function> } Eof
<function>    ::= <Keyword> Identifier Openround Closeround
                  <codeblock>
<datatype>    ::= Keyword(int)
<codeblock>   ::= Opencurly { <statement> } Closecurly
<statement>   ::= <returnstm> Semicolon
<returnstm>   ::= Keyword(return) expression
<expression>  ::= Numberconstant